# Generated by Django 4.1.7 on 2023-11-24 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crud_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "permissions": [
                    ("can_add_blog", "Can add blog"),
                    ("can_change_blog", "Can change blog"),
                    ("can_delete_blog", "Can delete blog"),
                    ("can_view_blog", "Can view blog"),
                ]
            },
        ),
    ]
