# Generated by Django 4.1.7 on 2023-11-28 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("crud_api", "0002_alter_blog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="created_by",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
