# Generated by Django 4.1.7 on 2023-11-28 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crud_api", "0003_blog_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
